version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting build process"
  build:
    commands:
      - echo "Triggering Lambda function to start AMI creation"
      - aws lambda invoke --function-name GoldenAMITriggerLambda /dev/null
  post_build:
    commands:
      - echo "Build completed successfully"
